
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  DbNull,
  JsonNull,
  AnyNull,
  NullTypes,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 7.7.0
 * Query Engine version: 75cbdc1eb7150937890ad5465d861175c6624711
 */
Prisma.prismaVersion = {
  client: "7.7.0",
  engine: "75cbdc1eb7150937890ad5465d861175c6624711"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull
Prisma.JsonNull = JsonNull
Prisma.AnyNull = AnyNull

Prisma.NullTypes = NullTypes



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.AdminProfileScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  isSuperAdmin: 'isSuperAdmin'
};

exports.Prisma.AuditLogScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  action: 'action',
  targetType: 'targetType',
  targetId: 'targetId',
  details: 'details',
  ipAddress: 'ipAddress',
  createdAt: 'createdAt'
};

exports.Prisma.BinomeInvitationScalarFieldEnum = {
  id: 'id',
  studentApplicationId: 'studentApplicationId',
  invitedStudentId: 'invitedStudentId',
  status: 'status',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt'
};

exports.Prisma.CompanyProfileScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  companyName: 'companyName',
  sector: 'sector',
  address: 'address',
  wilaya: 'wilaya',
  contactPhone: 'contactPhone',
  supervisorTitle: 'supervisorTitle'
};

exports.Prisma.DeadlineScalarFieldEnum = {
  id: 'id',
  title: 'title',
  type: 'type',
  dueDate: 'dueDate',
  internshipId: 'internshipId',
  isGlobal: 'isGlobal',
  academicYear: 'academicYear',
  createdById: 'createdById',
  createdAt: 'createdAt'
};

exports.Prisma.DefenseScalarFieldEnum = {
  id: 'id',
  internshipId: 'internshipId',
  scheduledAt: 'scheduledAt',
  room: 'room',
  timeSlot: 'timeSlot',
  status: 'status',
  gradesFinalized: 'gradesFinalized',
  finalGrade: 'finalGrade',
  mention: 'mention',
  adminGradeOverride: 'adminGradeOverride',
  overrideComment: 'overrideComment'
};

exports.Prisma.DocumentScalarFieldEnum = {
  id: 'id',
  internshipId: 'internshipId',
  uploadedById: 'uploadedById',
  type: 'type',
  fileName: 'fileName',
  fileUrl: 'fileUrl',
  fileSize: 'fileSize',
  version: 'version',
  status: 'status',
  reviewComment: 'reviewComment',
  reviewedById: 'reviewedById',
  uploadedAt: 'uploadedAt'
};

exports.Prisma.EvaluationScalarFieldEnum = {
  id: 'id',
  defenseId: 'defenseId',
  evaluatorId: 'evaluatorId',
  reportScore: 'reportScore',
  technicalScore: 'technicalScore',
  oralScore: 'oralScore',
  companyScore: 'companyScore',
  finalGrade: 'finalGrade',
  feedback: 'feedback',
  isAdvisory: 'isAdvisory',
  submittedAt: 'submittedAt'
};

exports.Prisma.InternshipScalarFieldEnum = {
  id: 'id',
  topicId: 'topicId',
  teacherId: 'teacherId',
  academicYear: 'academicYear',
  status: 'status',
  startDate: 'startDate',
  endDate: 'endDate',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.InternshipStudentScalarFieldEnum = {
  id: 'id',
  internshipId: 'internshipId',
  studentId: 'studentId',
  isLeader: 'isLeader'
};

exports.Prisma.JuryMemberScalarFieldEnum = {
  id: 'id',
  defenseId: 'defenseId',
  userId: 'userId',
  role: 'role',
  isAdvisory: 'isAdvisory',
  createdAt: 'createdAt'
};

exports.Prisma.MessageScalarFieldEnum = {
  id: 'id',
  internshipId: 'internshipId',
  senderId: 'senderId',
  content: 'content',
  attachmentUrl: 'attachmentUrl',
  attachmentName: 'attachmentName',
  attachmentSize: 'attachmentSize',
  requiresAction: 'requiresAction',
  actionType: 'actionType',
  actionStatus: 'actionStatus',
  actionById: 'actionById',
  sentAt: 'sentAt'
};

exports.Prisma.MessageReadScalarFieldEnum = {
  id: 'id',
  messageId: 'messageId',
  userId: 'userId',
  readAt: 'readAt'
};

exports.Prisma.MiniPresentationScalarFieldEnum = {
  id: 'id',
  internshipId: 'internshipId',
  title: 'title',
  scheduledAt: 'scheduledAt',
  room: 'room',
  timeSlot: 'timeSlot',
  documentDeadline: 'documentDeadline',
  status: 'status',
  documentUrl: 'documentUrl',
  documentName: 'documentName',
  submittedAt: 'submittedAt',
  adminComment: 'adminComment',
  createdAt: 'createdAt'
};

exports.Prisma.PasswordResetTokenScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  email: 'email',
  code: 'code',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt'
};

exports.Prisma.NotificationScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  type: 'type',
  title: 'title',
  message: 'message',
  isRead: 'isRead',
  emailSent: 'emailSent',
  relatedId: 'relatedId',
  relatedType: 'relatedType',
  createdAt: 'createdAt'
};

exports.Prisma.RegistrationRequestScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  password: 'password',
  role: 'role',
  motivation: 'motivation',
  companyName: 'companyName',
  studentId: 'studentId',
  promotion: 'promotion',
  speciality: 'speciality',
  academicYear: 'academicYear',
  grade: 'grade',
  sector: 'sector',
  wilaya: 'wilaya',
  status: 'status',
  adminComment: 'adminComment',
  userId: 'userId',
  createdAt: 'createdAt',
  reviewedAt: 'reviewedAt'
};

exports.Prisma.StudentApplicationScalarFieldEnum = {
  id: 'id',
  topicId: 'topicId',
  leaderId: 'leaderId',
  partnerId: 'partnerId',
  status: 'status',
  appliedAt: 'appliedAt',
  reviewedAt: 'reviewedAt'
};

exports.Prisma.StudentProfileScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  studentId: 'studentId',
  promotion: 'promotion',
  speciality: 'speciality',
  academicYear: 'academicYear'
};

exports.Prisma.SystemSettingsScalarFieldEnum = {
  id: 'id',
  key: 'key',
  value: 'value',
  updatedAt: 'updatedAt'
};

exports.Prisma.TeacherApplicationScalarFieldEnum = {
  id: 'id',
  teacherId: 'teacherId',
  topicId: 'topicId',
  message: 'message',
  status: 'status',
  appliedAt: 'appliedAt'
};

exports.Prisma.TeacherProfileScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  speciality: 'speciality',
  grade: 'grade',
  maxStudents: 'maxStudents',
  currentLoad: 'currentLoad',
  isAvailable: 'isAvailable'
};

exports.Prisma.TopicScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  requiredSkills: 'requiredSkills',
  type: 'type',
  status: 'status',
  maxStudents: 'maxStudents',
  academicYear: 'academicYear',
  proposedById: 'proposedById',
  assignedTeacherId: 'assignedTeacherId',
  supervisorRejectionCount: 'supervisorRejectionCount',
  resubmissionCount: 'resubmissionCount',
  maxResubmissions: 'maxResubmissions',
  rejectionReason: 'rejectionReason',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  password: 'password',
  role: 'role',
  avatarUrl: 'avatarUrl',
  isActive: 'isActive',
  mustChangePassword: 'mustChangePassword',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ValidationScalarFieldEnum = {
  id: 'id',
  topicId: 'topicId',
  validatorId: 'validatorId',
  step: 'step',
  status: 'status',
  comment: 'comment',
  validatedAt: 'validatedAt',
  createdAt: 'createdAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.AdminProfileOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.AuditLogOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  action: 'action',
  targetType: 'targetType',
  targetId: 'targetId',
  details: 'details',
  ipAddress: 'ipAddress'
};

exports.Prisma.BinomeInvitationOrderByRelevanceFieldEnum = {
  id: 'id',
  studentApplicationId: 'studentApplicationId',
  invitedStudentId: 'invitedStudentId'
};

exports.Prisma.CompanyProfileOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  companyName: 'companyName',
  sector: 'sector',
  address: 'address',
  wilaya: 'wilaya',
  contactPhone: 'contactPhone',
  supervisorTitle: 'supervisorTitle'
};

exports.Prisma.DeadlineOrderByRelevanceFieldEnum = {
  id: 'id',
  title: 'title',
  internshipId: 'internshipId',
  academicYear: 'academicYear',
  createdById: 'createdById'
};

exports.Prisma.DefenseOrderByRelevanceFieldEnum = {
  id: 'id',
  internshipId: 'internshipId',
  room: 'room',
  timeSlot: 'timeSlot',
  mention: 'mention',
  overrideComment: 'overrideComment'
};

exports.Prisma.DocumentOrderByRelevanceFieldEnum = {
  id: 'id',
  internshipId: 'internshipId',
  uploadedById: 'uploadedById',
  fileName: 'fileName',
  fileUrl: 'fileUrl',
  reviewComment: 'reviewComment',
  reviewedById: 'reviewedById'
};

exports.Prisma.EvaluationOrderByRelevanceFieldEnum = {
  id: 'id',
  defenseId: 'defenseId',
  evaluatorId: 'evaluatorId',
  feedback: 'feedback'
};

exports.Prisma.InternshipOrderByRelevanceFieldEnum = {
  id: 'id',
  topicId: 'topicId',
  teacherId: 'teacherId',
  academicYear: 'academicYear'
};

exports.Prisma.InternshipStudentOrderByRelevanceFieldEnum = {
  id: 'id',
  internshipId: 'internshipId',
  studentId: 'studentId'
};

exports.Prisma.JuryMemberOrderByRelevanceFieldEnum = {
  id: 'id',
  defenseId: 'defenseId',
  userId: 'userId'
};

exports.Prisma.MessageOrderByRelevanceFieldEnum = {
  id: 'id',
  internshipId: 'internshipId',
  senderId: 'senderId',
  content: 'content',
  attachmentUrl: 'attachmentUrl',
  attachmentName: 'attachmentName',
  actionType: 'actionType',
  actionStatus: 'actionStatus',
  actionById: 'actionById'
};

exports.Prisma.MessageReadOrderByRelevanceFieldEnum = {
  id: 'id',
  messageId: 'messageId',
  userId: 'userId'
};

exports.Prisma.MiniPresentationOrderByRelevanceFieldEnum = {
  id: 'id',
  internshipId: 'internshipId',
  title: 'title',
  room: 'room',
  timeSlot: 'timeSlot',
  documentUrl: 'documentUrl',
  documentName: 'documentName',
  adminComment: 'adminComment'
};

exports.Prisma.PasswordResetTokenOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  email: 'email',
  code: 'code'
};

exports.Prisma.NotificationOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  title: 'title',
  message: 'message',
  relatedId: 'relatedId',
  relatedType: 'relatedType'
};

exports.Prisma.RegistrationRequestOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  password: 'password',
  motivation: 'motivation',
  companyName: 'companyName',
  studentId: 'studentId',
  promotion: 'promotion',
  speciality: 'speciality',
  academicYear: 'academicYear',
  grade: 'grade',
  sector: 'sector',
  wilaya: 'wilaya',
  adminComment: 'adminComment',
  userId: 'userId'
};

exports.Prisma.StudentApplicationOrderByRelevanceFieldEnum = {
  id: 'id',
  topicId: 'topicId',
  leaderId: 'leaderId',
  partnerId: 'partnerId'
};

exports.Prisma.StudentProfileOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  studentId: 'studentId',
  promotion: 'promotion',
  speciality: 'speciality',
  academicYear: 'academicYear'
};

exports.Prisma.SystemSettingsOrderByRelevanceFieldEnum = {
  id: 'id',
  key: 'key',
  value: 'value'
};

exports.Prisma.TeacherApplicationOrderByRelevanceFieldEnum = {
  id: 'id',
  teacherId: 'teacherId',
  topicId: 'topicId',
  message: 'message'
};

exports.Prisma.TeacherProfileOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  speciality: 'speciality',
  grade: 'grade'
};

exports.Prisma.TopicOrderByRelevanceFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  requiredSkills: 'requiredSkills',
  academicYear: 'academicYear',
  proposedById: 'proposedById',
  assignedTeacherId: 'assignedTeacherId',
  rejectionReason: 'rejectionReason'
};

exports.Prisma.UserOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  password: 'password',
  avatarUrl: 'avatarUrl'
};

exports.Prisma.ValidationOrderByRelevanceFieldEnum = {
  id: 'id',
  topicId: 'topicId',
  validatorId: 'validatorId',
  comment: 'comment'
};
exports.binomeinvitation_status = exports.$Enums.binomeinvitation_status = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  DECLINED: 'DECLINED',
  EXPIRED: 'EXPIRED'
};

exports.deadline_type = exports.$Enums.deadline_type = {
  TOPIC_SUBMISSION: 'TOPIC_SUBMISSION',
  MID_REPORT: 'MID_REPORT',
  FINAL_REPORT: 'FINAL_REPORT',
  MINI_PRESENTATION: 'MINI_PRESENTATION',
  DEFENSE: 'DEFENSE'
};

exports.defense_status = exports.$Enums.defense_status = {
  SCHEDULED: 'SCHEDULED',
  HELD: 'HELD',
  POSTPONED: 'POSTPONED',
  CANCELLED: 'CANCELLED'
};

exports.document_type = exports.$Enums.document_type = {
  PROGRESS_REPORT: 'PROGRESS_REPORT',
  MID_REPORT: 'MID_REPORT',
  FINAL_REPORT: 'FINAL_REPORT',
  OTHER: 'OTHER'
};

exports.document_status = exports.$Enums.document_status = {
  UPLOADED: 'UPLOADED',
  REVIEWED: 'REVIEWED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED'
};

exports.internship_status = exports.$Enums.internship_status = {
  APPROVED: 'APPROVED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
};

exports.jurymember_role = exports.$Enums.jurymember_role = {
  PRESIDENT: 'PRESIDENT',
  RAPPORTEUR: 'RAPPORTEUR',
  EXAMINATEUR: 'EXAMINATEUR',
  COMPANY_ADVISOR: 'COMPANY_ADVISOR'
};

exports.minipresentation_status = exports.$Enums.minipresentation_status = {
  SCHEDULED: 'SCHEDULED',
  DOCUMENT_SUBMITTED: 'DOCUMENT_SUBMITTED',
  REVIEWED: 'REVIEWED',
  HELD: 'HELD',
  POSTPONED: 'POSTPONED',
  CANCELLED: 'CANCELLED'
};

exports.notification_type = exports.$Enums.notification_type = {
  REGISTRATION_SUBMITTED: 'REGISTRATION_SUBMITTED',
  REGISTRATION_APPROVED: 'REGISTRATION_APPROVED',
  REGISTRATION_REJECTED: 'REGISTRATION_REJECTED',
  TOPIC_SUBMITTED: 'TOPIC_SUBMITTED',
  TOPIC_APPROVED: 'TOPIC_APPROVED',
  TOPIC_REJECTED: 'TOPIC_REJECTED',
  TEACHER_ASSIGNED: 'TEACHER_ASSIGNED',
  TEACHER_ACCEPTED: 'TEACHER_ACCEPTED',
  TEACHER_REJECTED: 'TEACHER_REJECTED',
  TOPIC_PUBLISHED: 'TOPIC_PUBLISHED',
  STUDENT_APPLIED: 'STUDENT_APPLIED',
  APPLICATION_APPROVED: 'APPLICATION_APPROVED',
  APPLICATION_REJECTED: 'APPLICATION_REJECTED',
  BINOME_INVITATION: 'BINOME_INVITATION',
  BINOME_ACCEPTED: 'BINOME_ACCEPTED',
  BINOME_DECLINED: 'BINOME_DECLINED',
  INTERNSHIP_STARTED: 'INTERNSHIP_STARTED',
  INTERNSHIP_COMPLETED: 'INTERNSHIP_COMPLETED',
  INTERNSHIP_CANCELLED: 'INTERNSHIP_CANCELLED',
  DOCUMENT_UPLOADED: 'DOCUMENT_UPLOADED',
  DOCUMENT_APPROVED: 'DOCUMENT_APPROVED',
  DOCUMENT_REJECTED: 'DOCUMENT_REJECTED',
  MESSAGE_RECEIVED: 'MESSAGE_RECEIVED',
  MINI_PRESENTATION_SCHEDULED: 'MINI_PRESENTATION_SCHEDULED',
  MINI_PRESENTATION_REMINDER: 'MINI_PRESENTATION_REMINDER',
  DEFENSE_SCHEDULED: 'DEFENSE_SCHEDULED',
  DEFENSE_UPDATED: 'DEFENSE_UPDATED',
  GRADE_AVAILABLE: 'GRADE_AVAILABLE',
  DEADLINE_APPROACHING: 'DEADLINE_APPROACHING',
  DEADLINE_OVERDUE: 'DEADLINE_OVERDUE',
  ACCOUNT_CREATED: 'ACCOUNT_CREATED',
  PASSWORD_RESET: 'PASSWORD_RESET'
};

exports.registrationrequest_role = exports.$Enums.registrationrequest_role = {
  STUDENT: 'STUDENT',
  COMPANY: 'COMPANY',
  TEACHER: 'TEACHER'
};

exports.registrationrequest_status = exports.$Enums.registrationrequest_status = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED'
};

exports.studentapplication_status = exports.$Enums.studentapplication_status = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED'
};

exports.teacherapplication_status = exports.$Enums.teacherapplication_status = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED'
};

exports.topic_type = exports.$Enums.topic_type = {
  STUDENT_PROPOSED: 'STUDENT_PROPOSED',
  COMPANY_PROPOSED: 'COMPANY_PROPOSED'
};

exports.topic_status = exports.$Enums.topic_status = {
  PENDING_ADMIN: 'PENDING_ADMIN',
  PENDING_TEACHER: 'PENDING_TEACHER',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  OPEN_FOR_SELECTION: 'OPEN_FOR_SELECTION',
  TAKEN: 'TAKEN'
};

exports.user_role = exports.$Enums.user_role = {
  STUDENT: 'STUDENT',
  TEACHER: 'TEACHER',
  COMPANY: 'COMPANY',
  ADMIN: 'ADMIN'
};

exports.validation_step = exports.$Enums.validation_step = {
  ADMIN: 'ADMIN',
  TEACHER: 'TEACHER',
  COMPANY: 'COMPANY',
  FINAL_ADMIN: 'FINAL_ADMIN'
};

exports.validation_status = exports.$Enums.validation_status = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED'
};

exports.Prisma.ModelName = {
  AdminProfile: 'AdminProfile',
  AuditLog: 'AuditLog',
  BinomeInvitation: 'BinomeInvitation',
  CompanyProfile: 'CompanyProfile',
  Deadline: 'Deadline',
  Defense: 'Defense',
  Document: 'Document',
  Evaluation: 'Evaluation',
  Internship: 'Internship',
  InternshipStudent: 'InternshipStudent',
  JuryMember: 'JuryMember',
  Message: 'Message',
  MessageRead: 'MessageRead',
  MiniPresentation: 'MiniPresentation',
  PasswordResetToken: 'PasswordResetToken',
  Notification: 'Notification',
  RegistrationRequest: 'RegistrationRequest',
  StudentApplication: 'StudentApplication',
  StudentProfile: 'StudentProfile',
  SystemSettings: 'SystemSettings',
  TeacherApplication: 'TeacherApplication',
  TeacherProfile: 'TeacherProfile',
  Topic: 'Topic',
  User: 'User',
  Validation: 'Validation'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
